contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://xqf.github.io"
canonifyurls = "false"
[taxonomies]
    tag = "tags"
    category = "categories"

[asciidoctor]
    safe = "0"

[menu]
[[menu.nav]]
	weight = "1"
	name = "Home"
	url = "/"
[[menu.nav]]
	weight = "2"
	name = "About"
	url = "/about"
[[menu.nav]]
	weight = "3"
	name = "Downloads"
	url = "/downloads"
[[menu.nav]]
	weight = "4"
	name = "Screenshots"
	url = "/screenshots"
[[menu.nav]]
	weight = "5"
	name = "VCS"
	url = "https://github.com/xqf/xqf"
[[menu.nav]]
	weight = "6"
	name = "Change Log"
	url = "/changelog"
[[menu.nav]]
	weight = "7"
	name = "Documentation"
	url = "/docs"
[[menu.nav]]
	weight = "8"
	name = "FAQs"
	url = "/docs#troubleshooting"
[[menu.nav]]
	weight = "9"
	name = "Links"
	url = "/links"
[[menu.nav]]
	weight = "10"
	name = "Support"
	url = "/support"
[[menu.nav]]
	weight = "11"
	name = "License"
	url = "/license"
